fix: Hotfix for decorator `@skey` introduced by #1394 (#1419)
- `Method.skey` must hold the entire skey_config, as it is used within
`Method.__call__`
- `Method.additional_descr` should be set to "skey"-name and not
"access" (copy&paste bug)

---
Originated from error:
```
[2025-02-19 11:34:06,036] /.../viur/core/request.py:375 [ERROR] ViUR has caught an unhandled exception!
[2025-02-19 11:34:06,037] /.../viur/core/request.py:376 [ERROR] string indices must be integers, not 'str'
Traceback (most recent call last):
  File "~/viur-core/src/viur/core/request.py", line 350, in _process
    self._route(path)
  File "~/viur-core/src/viur/core/request.py", line 632, in _route
    res = caller(*self.args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/viur-core/src/viur/core/module.py", line 199, in __call__
    if self.skey and param_name == self.skey["forward_payload"]:
                                   ~~~~~~~~~^^^^^^^^^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'
```