fix: `BaseBone._get_distinct_hash` (#1662)
The feature introduced by #1228 didn't work under all circumstances.
This version should be much more robust. It changes signatures, but it
won't be a problem due current lack of feature use.

In this case, a RecordBone containing a RelationalBone failed with
```
File ".venv/lib/python3.13/site-packages/viur/core/bones/relational.py", line 483, in _get_single_destinct_hash
    parts = [value["dest"]["key"]]
             ~~~~~^^^^^^^^
TypeError: string indices must be integers, not 'str'
```