fix: multiple bones with languages have the wrong default value (#1282)
The language value needs to be a `list` as default value, not `None`.

A simple add failed already on unserialize:
```py
skel = ExampleSkel()
skel.write()
```


```py
[2024-10-10 02:06:18,911] viur/core/skeleton.py:1208 [ERROR] Failed to serialize Test_Bone_select_multi_lang <viur.core.bones.select.SelectBone object at 0x7fd69253ee40> {'de': None, 'en': None}
[2024-10-10 02:06:18,947] viur/core/request.py:331 [ERROR] ViUR has caught an unhandled exception!
[2024-10-10 02:06:18,947] viur/core/request.py:332 [ERROR] 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/.../deploy/viur/core/request.py", line 306, in _process
    self._route(path)
  File "/.../deploy/viur/core/request.py", line 565, in _route
    res = caller(*self.args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../deploy/viur/core/module.py", line 301, in __call__
    return self._func(self._instance, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../deploy/modules/example.py", line 208, in test_add1
    assert skel.write()
           ^^^^^^^^^^^^
  File "/.../deploy/viur/core/skeleton.py", line 1400, in write
    key, skel, change_list, is_add = db.RunInTransaction(__txn_write, skel)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "src/viur/datastore/transport.pyx", line 819, in viur.datastore.transport.RunInTransaction
  File "src/viur/datastore/transport.pyx", line 816, in viur.datastore.transport.RunInTransaction
  File "/.../deploy/viur/core/skeleton.py", line 1206, in __txn_write
    bone.serialize(skel, bone_name, True)
  File "/.../deploy/viur/core/bones/base.py", line 776, in serialize
    for singleValue in newVal[language]:
                       ~~~~~~^^^^^^^^^^
TypeError: 'NoneType' object is not iterable
```

Discovered during testing
https://github.com/viur-framework/viur-core/pull/1267