fix: Import Testbed on dev-server only
This fixes the following bug that raises in lately updated ViUR environments and requires a manual dependency intervention on (deprecated) rsa:

```
File "~/myproject/deploy/main.py", line 1, in <module>
    from viur import core
  File "~/myproject/.venv/lib/python3.13/site-packages/viur/core/__init__.py", line 18, in <module>
    from viur.core import i18n, request, utils
  File "~/myproject/.venv/lib/python3.13/site-packages/viur/core/i18n.py", line 86, in <module>
    from viur.core import current, db, languages, tasks
  File "~/myproject/.venv/lib/python3.13/site-packages/viur/core/db/__init__.py", line 4, in <module>
    from . import cache
  File "~/myproject/.venv/lib/python3.13/site-packages/viur/core/db/cache.py", line 3, in <module>
    from google.appengine.ext.testbed import Testbed
  File "~/myproject/.venv/lib/python3.13/site-packages/google/appengine/ext/testbed/__init__.py", line 127, in <module>
    from google.appengine.api.app_identity import app_identity_stub
  File "~/myproject/.venv/lib/python3.13/site-packages/google/appengine/api/app_identity/app_identity_stub.py", line 35, in <module>
    from google.appengine.api.app_identity import app_identity_defaultcredentialsbased_stub as ai_default_stub
  File "~/myproject/.venv/lib/python3.13/site-packages/google/appengine/api/app_identity/app_identity_defaultcredentialsbased_stub.py", line 31, in <module>
    from google.appengine.api.app_identity import app_identity_stub_base
  File "~/myproject/.venv/lib/python3.13/site-packages/google/appengine/api/app_identity/app_identity_stub_base.py", line 42, in <module>
    import rsa
ModuleNotFoundError: No module named 'rsa'
```