fix: import qrcode's element with an alias
There was a name conflict between the imported `qrcode` package and the
jinja function `qrcode`.

```py
[2023-09-08 21:37:26,287] main.py:119 [ERROR] 'function' object has no attribute 'make'
Traceback (most recent call last):
  [...]
    {{ qrcode(otp_uri) }}
  File "/project/deploy/viur/core/render/html/env/viur.py", line 742, in qrcode
    return qrcode.make(data, image_factory=qrcode.image.svg.SvgPathImage, box_size=30).to_string().decode("utf-8")
AttributeError: 'function' object has no attribute 'make'
```