fix(cicd): Add RSA package (#1650)
There goes something wrong. Not sure why it's missing, but this should
fix it:
```
ImportError: Failed to import test module: tests.test_config
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.13.12/x64/lib/python3.13/unittest/loader.py", line 396, in _find_test_path
    module = self._get_module_from_name(name)
  File "/opt/hostedtoolcache/Python/3.13.12/x64/lib/python3.13/unittest/loader.py", line 339, in _get_module_from_name
    __import__(name)
    ~~~~~~~~~~^^^^^^
  File "/home/runner/work/viur-core/viur-core/viur/tests/test_config.py", line 3, in <module>
    from abstract import ViURTestCase
  File "/home/runner/work/viur-core/viur-core/viur/tests/abstract.py", line 5, in <module>
    from google.appengine.ext import testbed
  File "/opt/hostedtoolcache/Python/3.13.12/x64/lib/python3.13/site-packages/google/appengine/ext/testbed/__init__.py", line 127, in <module>
    from google.appengine.api.app_identity import app_identity_stub
  File "/opt/hostedtoolcache/Python/3.13.12/x64/lib/python3.13/site-packages/google/appengine/api/app_identity/app_identity_stub.py", line 35, in <module>
    from google.appengine.api.app_identity import app_identity_defaultcredentialsbased_stub as ai_default_stub
  File "/opt/hostedtoolcache/Python/3.13.12/x64/lib/python3.13/site-packages/google/appengine/api/app_identity/app_identity_defaultcredentialsbased_stub.py", line 31, in <module>
    from google.appengine.api.app_identity import app_identity_stub_base
  File "/opt/hostedtoolcache/Python/3.13.12/x64/lib/python3.13/site-packages/google/appengine/api/app_identity/app_identity_stub_base.py", line 42, in <module>
    import rsa
ModuleNotFoundError: No module named 'rsa'
```