fix: Hotfix for #1391: missing skeltype-check (#1420)
Pull request #1391 introduced this bug coming up when creating a FOLDER!
```
[2025-02-19 11:41:33,257] /.../viur/core/request.py:375 [ERROR] ViUR has caught an unhandled exception!
[2025-02-19 11:41:33,257] /.../viur/core/request.py:376 [ERROR] 'NoneType' object has no attribute 'startswith'
Traceback (most recent call last):
  File "~/viur-core/src/viur/core/request.py", line 350, in _process
    self._route(path)
  File "~/viur-core/src/viur/core/request.py", line 632, in _route
    res = caller(*self.args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/viur-core/src/viur/core/module.py", line 236, in __call__
    return self._func(self._instance, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/viur-core/src/viur/core/modules/file.py", line 1214, in add
    return super().add(skelType, node, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/viur-core/src/viur/core/module.py", line 236, in __call__
    return self._func(self._instance, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/viur-core/src/viur/core/prototypes/tree.py", line 458, in add
    self.onAdded(skelType, skel)
  File "~/viur-core/src/viur/core/modules/file.py", line 1288, in onAdded
    if skel["mimetype"].startswith("image/"):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'startswith'
```