refactor: `__build_app` function clean-up and make all modules accessible
This is both a refactor and a fix for the `Modulename.html = True` default that was removed with viur-core 3.6.

The error `AttributeError: 'Index' object has no attribute '<modulename>'` is fixed with this improvement, and the workaround of `conf.main_app.vi.modulename` is not neccessary anymore.